module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './Components/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'kaltire-red': '#f15a22',
        'regal-blue': '#243c5a',
        'tire-dark': '#24252D',
        'tire-gray-1': '#E3E1E3',
        'tire-gray-2': '#888888',
        'tire-gray-3': '#222121',
        'tire-black-1': '#2D2E36',
        'tire-black-2': '#1B1A21',
        'tire-black-3': '#2A2D3A',
        'tire-black-4': '#24252D',
        'tire-red-violet': '#DA18A3',
        'file-active': '#2196f3',
        'file-accept': '#00e676',
        'file-reject': '#ff1744',
        'overlay-black': 'rgba(0, 0, 0, 0.8)',
        'bg-white-1': '#FFFFFF',
        'onsite-text': '#514A4A',
        'onsite-heading': '#323232',
        'speciality-background': '#ffffff00',
        departmentheading: '#565967',
        perkbenefitsborder: '#BFBFBF',
        ykvldesc: '#4A4A4D',
        resumeheading: '#474747',
        resumedescription: '#514A4A',
        contactredtwo: '#f15a22',
        PrimaryTwo: '#0076C8',
        Lightbox: '#000000d6',
        Roadsidetxt: '#ffffffa3',
        locationGrey: '#2C2C2C',
      },
      gridTemplateColumns: {
        onsiteTemplate: 'repeat(4, minmax(250px, 1fr))',
        PerkTemplate: 'repeat(4, minmax(200px, 1fr))',
        perkTemplatetwo: 'repeat(auto-fit,minmax(200px.1fr))',
        PerkTemplatetab: 'repeat(1, minmax(250px, 1fr))',
        PerkTemplatemobile: 'repeat(1, minmax(200px, 1fr))',
        onsiteTemplate2: 'repeat(auto-fit, minmax(300px, 1fr))',
        servicesTemplate: 'repeat(4, minmax(0, 1fr))',
        DepartmentsTemplate: 'repeat(6, minmax(0, 1fr))',
        DepartmentsTemplateTwo: 'repeat(3, minmax(0, 1fr))',
        // servicesTabTemplate: 'repeat(2,minmax(0,1fr))',
        servicesTabTemplate: 'repeat(0,minmax(0,1fr))',
        servicesMobileTemplate: 'repeat(1,minmax(0,1fr))',
        onsiteTemplatetab: 'repeat(3, minmax(250px, 1fr))',
        onsiteTemplatemobile: 'repeat(1, minmax(250px, 1fr))',
      },
      // gridTemplateRows: {
      //   onsiterowTemplate: 'repeat(5,1fr)',
      // },

      width: {
        215: '215px',
        357: '357px',
        557: '557px',
        InputPrac: '78%',
        onsiteimage: '125px',
        perkimagewidth: '6.75rem',
        contactwidthmobile: '22rem',
        locationsection: '25rem',
      },
      backgroundImage: {
        'footer-texture':
          "url('https://raw.githubusercontent.com/kalfreight-in/BigRigGroups/master/src/assets/Images/abouthomeimage.png')",
      },
      zIndex: {
        n2: -2,
        n1: -1,
      },
      minWidth: {
        155: '155px',
        190: '190px',
        215: '215px',
        240: '240px',
        256: '256px',
        327: '327px',
      },
      padding: {
        lightboxtabpadding: '28rem',
        lightboxmobilepadding: '28rem',
      },
      height: {
        300: '300px',
        557: '557px',
        mapheightFull: '900px',
        mapScrollheightFull: '600px',
        mapheightMob: '800px',
        Onsiteheight: '95vh',
        onsitegridheight: '75vh',
        onsiteimage: '140px',
        perkimageheight: '7.5rem',
        contactheighttab: '6rem',
        contactheightmobile: '4.5rem',
        heading: '3rem',
        subheading: '1.6rem',
        careerheaderHeight: '60vh',
        careerheaderMobileH: '40vh',
        navsmall: '14px',
        navsmallne: '10px;',
        descnew: '1rem',
        highheight: '42 rem',
      },

      inset: {
        45: '45%',
        65: '65px',
        navbargap: '4.9rem',
      },
      spacing: {
        65: '65px',
      },
      flex: {
        2: '2 2 0%',
      },
      lineHeight: {
        70: '70px',
      },
      zIndex: {
        '-5': '-5',
        0: '0',
      },
      fontSize: {
        contactheading: '2.5rem',
        careeremail: '1.10rem',
      },
    },
    // screens: {
    //   lg: { max: '1800px' },
    //   md: { max: '990px' },
    //   sm: { max: '600px' },
    //   xs: { max: '400px' },
    //   minmd: '1700px',
    //   minlg: '2100px',
    // },
    fontFamily: {
      // poppins: ['Poppins', 'sans-serif'],
      Helvetica: ['Helvetica'],
      poppins: ['Poppins', 'sans-serif'],
      cursive: [' cursive'],
      Verdana: ['Verdana, Arial, Tahoma, Serif'],
    },
  },
  variants: {
    extend: {},
  },
  plugins: [
    'tailwindcss',
    'postcss-flexbugs-fixes',
    [
      'postcss-preset-env',
      {
        autoprefixer: {
          flexbox: 'no-2009',
        },
        stage: 3,
        features: {
          'custom-properties': false,
        },
      },
    ],
  ],
};
